CREATE TABLE UTILISATEUR(
   idUtil int,
   email VARCHAR(50) NOT NULL,
   mdp VARCHAR(100) NOT NULL,
   nomUtil VARCHAR(50) NOT NULL,
   prenom VARCHAR(50) NOT NULL,
   PRIMARY KEY(idUtil)
);

CREATE TABLE JEU(
   idJeux int,
   nomJeux VARCHAR(50) NOT NULL,
   dateSorti DATE NOT NULL,
   editeur VARCHAR(50) NOT NULL,
   descr TEXT,
   URLCover VARCHAR(150) NOT NULL,
   URLSite VARCHAR(100) NOT NULL,
   PRIMARY KEY(idJeux)
);

CREATE TABLE BIBLIOTHEQUE(
   idBibli SMALLINT,
   heureDeJeu DECIMAL(4,2) NOT NULL,
   idUtil int NOT NULL,
   idJeux int NOT NULL,
   PRIMARY KEY(idBibli),
   FOREIGN KEY(idUtil) REFERENCES UTILISATEUR(idUtil),
   FOREIGN KEY(idJeux) REFERENCES JEU(idJeux)
);
